### PR TITLE
added in the support for getting the publisher

### PR DESCRIPTION
**Pull request by gedankenstuecke**
following the wish in #1 I added back in the journal publisher as well :smile:

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
btw. anything else that needs work? :smiley:

**Comment by FotoVerite** [comment]
Sorry been flying around like mad planning to get this all pushed to rubygems today

**Comment by FotoVerite** [comment]
Please don't bump version on PR's

**Comment by gedankenstuecke** [comment]
No problem! And sorry for bumping the version! :-)

**Pull request merged**
